name: raw_image_provider
description: Support Image widget to load the raw image pixels data
version: 0.2.0
homepage: https://github.com/yrom/flutter_raw_image_provider/

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

